### ISSUE TITLE
error

### ISSUE THREAD

**Issue by MartinP7r** [xiaohk/clip2imgur#4]
Hi there!   
Awesome tool! Thanks for providing this 😄 

I'm currently getting an error

```
Uploading...
Error: Failed to upload image with codeOptional(400)
```

But can't really figure out why. Is there a `--verbose` type of option to see the actual error message?

**Comment by xiaohk** [comment]
Hi! Thanks for reaching out! I can't debug this error because I can't compile the 6 year old Swift code any more 😭.

I just rewrote Clip2imgur using Python, and updated the Homebrew formula. You can try to upgrade clip2imgur with `brew upgrade clip2imgur`, or try to re-install it. Let me know if it doesn't work! Thanks!
